//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stajprojem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserWorks
    {
        public int Id { get; set; }
        public int UsersId { get; set; }
        public int WorksId { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> ActualEffort { get; set; }
        public Nullable<int> AssignedEffort { get; set; }
        public Nullable<int> RemainingEfort { get; set; }
        public Nullable<System.DateTime> CreatedTime { get; set; }
        public Nullable<System.DateTime> LastUpdateTime { get; set; }
        public string UpdateExplanation { get; set; }
        public string Status { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Works Works { get; set; }
    }
}
